theme: jekyll-theme-minimal
title: Bancos Brasileiros - MergeTool
description: ğŸ‡§ğŸ‡· ğŸ¦ ğŸ“‹ Brazilian banks Merge Tool
logo: https://raw.githubusercontent.com/guibranco/BancosBrasileiros-MergeTool/main/logo.png
show_downloads: true
